# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: A to Z CSS
description: Learn CSS and sharpen your front-end skills with this totally free 26-part video series
url: www.atozcss.com

permalink: /:categories/:title
links:
    - title: Home
      url: /
    - title: All Episodes
      url: episodes.html
    - title: About
      url: about.html
    - title: Subscribe
      url: subscribe.html

pygments: true
paginate: 10 # pagination basted on number of posts

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

