# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: A to Z CSS
description: Learn CSS and sharpen your front-end skills with this totally free 26-part video series
url: www.atozcss.com
disqusName: atozcss

permalink: /:categories/:title
links:
    - title: Videos
      url: /videos
    - title: Blog
      url: /blog
    - title: Start Here
      url: /start-here
    - title: Resources
      url: /resources
    - title: About
      url: /about

highlighter: pygments
paginate: 10 # pagination basted on number of posts

safe: false
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'node_modules'] # files to exclude

