# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: A to Z CSS
description: Supercharge your front-end skills. Level up your CSS and Sass with bite-sized videos, weekly news and in-depth books & training courses.
url: www.atozcss.com
disqusName: atozcss

permalink: /:categories/:title
links:
    - title: Videos
      url: /videos
    - title: Articles
      url: /blog
    - title: Books
      url: /books
    - title: Courses
      url: /courses

highlighter: pygments
paginate: 10 # pagination basted on number of posts

safe: false
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'node_modules'] # files to exclude

